### ISSUE TITLE
Preview not displaying icon

### ISSUE THREAD

**Issue by indiejames** [Microsoft/extension-manifest-editor#13]
I have the following entry in my package.json: 
```json
"icon": "images/icon.png"
```
and the icon.png file is in the images sub directory. When I build a vsix file and install it I see my icon in the extensions view, but it does not show up in the manifest prevew. Instead I get a broken link with text "Invalid image path". 

This is VS Code 1.8.1 on OS X.

**Comment by hangxingliu** [comment]
Bug about "Invalid image path" also appeared in VS Code 1.11.1 on Ubuntu;

**Comment by nirmalapemireddy** [comment]
Thanks for reporting the issue. Will work on fixing this ASAP.

**Comment by nirmalapemireddy** [comment]
issue is resolved. Please update to latest version 0.1.4

**Comment by webstractions** [comment]
I am getting this same issue "Invalid image path" on Windows 10 and VSCode 1.24.1
