### ISSUE TITLE
command 'extension.generateStandalonePreview' not found

### ISSUE THREAD

**Issue by robertoachar** [Microsoft/extension-manifest-editor#15]
I get this message when I try to use the extension.

**Comment by nirmalapemireddy** [comment]
I'm unable to repro the issue on Window OS. Can you please share your OS details
If Possible share the extension Json file with us.

**Comment by robertoachar** [comment]
Hi,

I don't know how, but the extension is working now. When I tried to use it for the first time, it did'n work. I am using a Windows 10 with the latest version of VS Code.

I tried a couple of things:
* Uninstall the extension
* Reload the editor
* Close the Code
* Open the Code
* Install the extension
* Reload the editor

The extension is still working. If I get this error again, I will keep in touch.

Thanks for reply.

**Comment by nirmalapemireddy** [comment]
closing the issues as there is not repro steps
