### ISSUE TITLE
Don't hijack Cmd-Q on OS X

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/extension-manifest-editor#5]
The extension hijacks <kbd>Cmd Q</kbd> on OS X, so now I can't quit Code any more. 😕

**Comment by nirmalapemireddy** [comment]
Thanks for reporting the issue. Will resolve it ASAP.

**Comment by nirmalapemireddy** [comment]
Issue is resolved now. cmd is replaced with ctrl
