### ISSUE TITLE
Preview needs to be updated to new Marketplace link names.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/extension-manifest-editor#7]
Change "Support" to "Issues"
Change "Get Started" to "Repository"
Change "Learn" to "Homepage"

**Comment by nirmalapemireddy** [comment]
working on fixing this

**Comment by gregvanl** [comment]
Thanks for working on this.  We're calling out this extension in our VS Code docs https://vscode-eastus.azurewebsites.net/docs/extensionAPI/extension-manifest#_marketplace-presentation-tips and it will be great to keep it up to date.

**Comment by nirmalapemireddy** [comment]
Thanks for listing out in vscode docs. Will try to keep it updated with marketplace page
